import { Item } from '@/types';

// Export the mock items directly
export const mockItems: Item[] = [
  {
    id: 'item_1',
    name: 'Rice (1kg)',
    price: 60,
    category: 'Groceries',
    description: 'Premium quality basmati rice',
    stock: 50,
    unit: 'kg',
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'item_2',
    name: 'Wheat Flour (1kg)',
    price: 40,
    category: 'Groceries',
    description: 'Whole wheat flour',
    stock: 30,
    unit: 'kg',
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'item_3',
    name: 'Sugar (1kg)',
    price: 45,
    category: 'Groceries',
    stock: 40,
    unit: 'kg',
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'item_4',
    name: 'Cooking Oil (1L)',
    price: 120,
    category: 'Groceries',
    description: 'Refined sunflower oil',
    stock: 25,
    unit: 'L',
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'item_5',
    name: 'Milk (1L)',
    price: 60,
    category: 'Dairy',
    stock: 20,
    unit: 'L',
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'item_6',
    name: 'Eggs (dozen)',
    price: 80,
    category: 'Dairy',
    stock: 15,
    unit: 'dozen',
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'item_7',
    name: 'Bread',
    price: 35,
    category: 'Bakery',
    stock: 10,
    unit: 'loaf',
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'item_8',
    name: 'Tomatoes (1kg)',
    price: 40,
    category: 'Vegetables',
    stock: 20,
    unit: 'kg',
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'item_9',
    name: 'Onions (1kg)',
    price: 30,
    category: 'Vegetables',
    stock: 30,
    unit: 'kg',
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'item_10',
    name: 'Potatoes (1kg)',
    price: 25,
    category: 'Vegetables',
    stock: 40,
    unit: 'kg',
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
];

// Keep the function for generating mock items
export const generateMockItems = (): Item[] => {
  return mockItems;
};